import test,{beforeEach,after} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {randomUUID} from 'node:crypto';
const directory=mkdtempSync(join(tmpdir(),'tla-game-'));process.env.DATA_DIR=directory;delete process.env.DATABASE_URL;
const {migrate,tx,q}=await import('../server/db.js');
const {act,tick,state,now,enqueue}=await import('../server/game.js');
const {fulfill}=await import('../server/payments.js');
await migrate();
beforeEach(async()=>{await tx(async db=>{for(const table of ['placements','audience','payments','payment_events','audit','outbox','sponsors'])await db(`DELETE FROM ${table}`);});await tick();});
after(()=>rmSync(directory,{recursive:true,force:true}));
async function queued(name='Product',sponsor='sponsor-1'){const id=randomUUID();await tx(db=>db("INSERT INTO placements(id,sponsor_id,name,headline,description,url,status,created_at,queued_at) VALUES(?,?,?,?,?,?,'queued',?,?)",[id,sponsor,name,'A headline','Some description','https://openai.com',now(),now()]));await tx(db=>enqueue(db,id));return id;}
test('duplicate audience actions count once under concurrent requests',async()=>{const p=(await state('visitor')).current;const results=await Promise.all(Array.from({length:20},()=>act(p.id,'visitor')));assert.equal(results.filter(r=>r.counted).length,1);assert.equal((await state('visitor')).current.remaining,499);assert.equal((await state('visitor')).acted,true);});
test('the last action transitions exactly once and stale requests do not hit successor',async()=>{const p=(await state('a')).current;const next=await queued();await tx(db=>db('UPDATE placements SET remaining=1 WHERE id=?',[p.id]));const results=await Promise.all(Array.from({length:10},(_,i)=>act(p.id,`v${i}`)));assert.equal(results.filter(r=>r.counted).length,1);assert.equal((await state('a')).current.id,next);assert.equal((await state('a')).current.remaining,500);assert.equal((await q("SELECT * FROM placements WHERE status='live'")).length,1);assert.equal((await q('SELECT remaining FROM placements WHERE id=?',[p.id]))[0].remaining,0);});
test('time expiry advances and preserves unspent actions in archive',async()=>{const p=(await state('a')).current;const next=await queued();await tx(db=>db('UPDATE placements SET expires_at=? WHERE id=?',[now()-1,p.id]));await tick();assert.equal((await state('a')).current.id,next);const [ended]=await q('SELECT * FROM placements WHERE id=?',[p.id]);assert.equal(ended.reason,'timeout');assert.equal(ended.remaining,500);});
test('same sponsor cannot occupy consecutive placements',async()=>{const first=await queued('First');const second=await queued('Second');const initial=(await state('a')).current;await tx(db=>db('UPDATE placements SET remaining=0 WHERE id=?',[initial.id]));await tick();assert.equal((await state('a')).current.id,first);await tx(db=>db('UPDATE placements SET remaining=0 WHERE id=?',[first]));await tick();assert.equal((await state('a')).current.house,1);const house=(await state('a')).current;await tx(db=>db('UPDATE placements SET remaining=0 WHERE id=?',[house.id]));await tick();assert.equal((await state('a')).current.id,second);});
async function payment(purpose,status='live'){
 const p=(await state('a')).current;await tx(async db=>{await db('UPDATE placements SET status=? WHERE id=?',[status,p.id]);await db("INSERT INTO payments(id,placement_id,sponsor_id,purpose,amount,state,created_at) VALUES(?,?,?,?,?,'pending',?)",['payment-1',p.id,'owner',purpose,purpose==='refill'?1000:2000,now()]);});return {p,session:{id:'cs_test',metadata:{paymentId:'payment-1'},payment_status:'paid',amount_total:purpose==='refill'?1000:2000,currency:'usd',payment_intent:'pi_test'}};
}
test('duplicate payment deliveries add a refill exactly once',async()=>{const {p,session}=await payment('refill');await Promise.all([fulfill(session,'evt-1'),fulfill(session,'evt-1'),fulfill(session,'evt-2')]);const [row]=await q('SELECT * FROM placements WHERE id=?',[p.id]);assert.equal(row.allowance,750);assert.equal(row.remaining,750);assert.equal(row.refilled,1);assert.equal((await q('SELECT state FROM payments WHERE id=?',['payment-1']))[0].state,'fulfilled');});
test('late refill queues a refund and never revives an ended ad',async()=>{const {p,session}=await payment('refill','ended');await fulfill(session,'evt-late');assert.equal((await q('SELECT status FROM placements WHERE id=?',[p.id]))[0].status,'ended');assert.equal((await q('SELECT state FROM payments WHERE id=?',['payment-1']))[0].state,'refund_pending');});
test('unpaid and wrong amount sessions never fulfill',async()=>{const {session}=await payment('refill');await fulfill({...session,payment_status:'unpaid'},'evt-unpaid');assert.equal((await q('SELECT state FROM payments WHERE id=?',['payment-1']))[0].state,'pending');await assert.rejects(()=>fulfill({...session,amount_total:1},'evt-invalid'),/amount mismatch/);assert.equal((await q('SELECT state FROM payments WHERE id=?',['payment-1']))[0].state,'pending');});
test('approved placement enters queue only after confirmed payment',async()=>{const {p,session}=await payment('placement','approved');await fulfill(session,'evt-paid');assert.equal((await q('SELECT status FROM placements WHERE id=?',[p.id]))[0].status,'queued');assert.equal((await q('SELECT state FROM payments WHERE id=?',['payment-1']))[0].state,'fulfilled');});
