import test from 'node:test';
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {randomBytes} from 'node:crypto';
import net from 'node:net';
const probe=net.createServer();await new Promise(r=>probe.listen(0,'127.0.0.1',r));const port=probe.address().port;await new Promise(r=>probe.close(r));
const directory=mkdtempSync(join(tmpdir(),'tla-http-'));const admin=randomBytes(32).toString('hex');
const child=spawn(process.execPath,['server/index.js'],{env:{...process.env,NODE_ENV:'test',DATA_DIR:directory,DATABASE_URL:'',PORT:String(port),ADMIN_TOKEN:admin,STRIPE_SECRET_KEY:'',PUBLIC_URL:''},stdio:['ignore','pipe','pipe']});
await new Promise((resolve,reject)=>{const timeout=setTimeout(()=>reject(new Error('Server startup timed out')),15000);child.stdout.on('data',d=>{if(d.toString().includes('listening')){clearTimeout(timeout);resolve();}});child.on('exit',c=>{clearTimeout(timeout);reject(new Error(`Server exited ${c}`));});child.stderr.on('data',d=>{if(!d.toString().includes('ExperimentalWarning')&&!d.toString().includes('trace-warnings'))process.stderr.write(d);});});
const base=`http://127.0.0.1:${port}`;
function client(){const jar=new Map();return async(path,method='GET',body,headers={})=>{const r=await fetch(base+path,{method,headers:{'Content-Type':'application/json',cookie:[...jar].map(([k,v])=>`${k}=${v}`).join('; '),...headers},body:body===undefined?undefined:JSON.stringify(body),redirect:'manual'});for(const c of r.headers.getSetCookie()){const first=c.split(';')[0],i=first.indexOf('=');jar.set(first.slice(0,i),first.slice(i+1));}const data=r.headers.get('content-type')?.includes('application/json')?await r.json():await r.text();return{status:r.status,data,headers:r.headers};};}
await test('HTTP journey: accounts, moderation, isolation, handoff, archive, security and payment gate',async()=>{
 const visitor=client(),owner=client(),other=client(),operator=client();
 assert.equal((await visitor('/api/health')).status,200);
 for(const path of ['/','/sponsor','/dashboard','/archive','/rules','/terms','/privacy','/admin']){const r=await visitor(path);assert.equal(r.status,200);assert.match(r.data,/<title>[^<]*The Last Ad/);assert.ok(r.headers.get('content-security-policy'));}
 assert.equal((await visitor('/api/dashboard')).status,401);
 assert.equal((await visitor('/api/admin')).status,401);
 const signed=(await visitor('/api/state')).data;assert.equal(signed.current.house,1);assert.ok(!('sponsor_id' in signed.current));
 assert.equal((await visitor(`/api/placements/${signed.current.id}/end`,'POST',{})).data.counted,true);
 assert.equal((await visitor(`/api/placements/${signed.current.id}/end`,'POST',{})).data.duplicate,true);
 assert.equal((await visitor(`/api/placements/${signed.current.id}/end`,'POST',{}, {origin:'https://evil.example'})).status,403);
 const pass=randomBytes(18).toString('hex');
 assert.equal((await owner('/api/auth/register','POST',{email:'owner@example.com',password:pass})).status,200);
 assert.equal((await other('/api/auth/register','POST',{email:'other@example.com',password:pass})).status,200);
 const creative={name:'Test Product',headline:'A GOOD IDEA HAS ARRIVED.',description:'An integration test product, never published to production.',url:'https://openai.com',theme:'blue',image:'',accepted:true};
 assert.equal((await owner('/api/submissions','POST',{...creative,url:'javascript:alert(1)'})).status,400);
 const created=await owner('/api/submissions','POST',creative);assert.equal(created.status,201);const id=created.data.id;
 assert.equal((await visitor(`/api/placements/${id}`)).status,404);
 assert.equal((await other('/api/dashboard')).data.placements.length,0);
 assert.equal((await other(`/api/placements/${id}/reuse`,'POST',{})).status,404);
 assert.equal((await owner(`/api/placements/${id}/checkout`,'POST',{purpose:'placement'})).status,503);
 assert.equal((await owner(`/api/placements/${id}/bid`,'POST',{roundId:signed.current.id,amount:500})).status,503);
 assert.equal((await other(`/api/placements/${id}/public-metrics`,'POST',{})).status,404);
 assert.equal((await visitor('/api/instrument','POST',{event:'made_up'})).status,400);
 const h={authorization:`Bearer ${admin}`};
 assert.equal((await operator(`/api/admin/placements/${id}`,'POST',{action:'approve',note:'Approved for test'},h)).status,200);
 assert.equal((await owner('/api/dashboard')).data.placements[0].status,'approved');
 assert.equal((await operator(`/api/admin/placements/${id}`,'POST',{action:'complimentary'},h)).status,200);
 assert.equal((await operator(`/api/admin/placements/${signed.current.id}`,'POST',{action:'end'},h)).status,200);
 const live=(await visitor('/api/state')).data;assert.equal(live.current.id,id);assert.equal(live.current.complimentary,1);
 assert.equal((await visitor(`/api/placements/${id}/end`,'POST',{})).data.counted,true);
 assert.equal((await visitor(`/api/placements/${id}/view`,'POST',{})).status,200);
 assert.equal((await visitor(`/go/${id}`)).status,302);
 assert.equal((await visitor(`/go/${id}`)).headers.get('location'),'https://openai.com');
 assert.equal((await visitor('/api/state')).data.current.views,null);
 assert.equal((await owner(`/api/placements/${id}/public-metrics`,'POST',{})).status,200);
 assert.equal((await visitor('/api/state')).data.current.views,1);
 const og=await visitor(`/og/${id}.png`);assert.equal(og.status,200);assert.match(og.headers.get('content-type'),/image\/png/);
 const metrics=(await owner('/api/dashboard')).data.placements[0];assert.equal(metrics.views,1);assert.equal(metrics.clicks,1);assert.equal(metrics.remaining,499);
 assert.equal((await operator(`/api/admin/placements/${id}`,'POST',{action:'end'},h)).status,200);
 assert.ok((await visitor('/api/archive')).data.items.some(p=>p.id===id));
 const card=await visitor(`/share/${id}.svg`);assert.equal(card.status,200);assert.match(card.data,/Test Product/);assert.match(card.data,/1 audience actions/);
 assert.equal((await owner('/api/auth/logout','POST',{})).status,200);assert.equal((await owner('/api/dashboard')).status,401);
 assert.equal((await owner('/api/auth/login','POST',{email:'owner@example.com',password:pass})).status,200);
});
child.kill('SIGTERM');await new Promise(r=>child.on('exit',r));rmSync(directory,{recursive:true,force:true});
