import express from 'express';
import helmet from 'helmet';
import { rateLimit, ipKeyGenerator } from 'express-rate-limit';
import multer from 'multer';
import sharp from 'sharp';
import { randomUUID } from 'node:crypto';
import { resolve } from 'node:path';
import { z } from 'zod';
import { q, tx, migrate, postgres } from './db.js';
import { RULES, now, tick, state, act, track, advance, publicPlacement, audit, notify, enqueue, finish } from './game.js';
import { token, hash, passwordHash, verifyPassword, cookies, setCookie, safeEqual, validUrl, signVisitor } from './security.js';
import { paymentsEnabled, stripe, checkout, fulfill, paymentWorker } from './payments.js';

await migrate();await tick();
await tx(db=>db('INSERT INTO settings(key,value) VALUES(?,?) ON CONFLICT DO NOTHING',['visitor_secret',token()]));
const [{value:visitorSecret}]=await q('SELECT value FROM settings WHERE key=?',['visitor_secret']);
const app=express();
app.disable('x-powered-by');
if(process.env.TRUST_PROXY)app.set('trust proxy',Number(process.env.TRUST_PROXY));
app.use(helmet({contentSecurityPolicy:{directives:{defaultSrc:["'self'"],imgSrc:["'self'","data:","blob:"],styleSrc:["'self'","'unsafe-inline'"],scriptSrc:["'self'"],connectSrc:["'self'"],fontSrc:["'self'"],frameAncestors:["'none'"]}}}));
app.post('/api/webhooks/stripe',express.raw({type:'application/json',limit:'1mb'}),async(req,res)=>{
  if(!paymentsEnabled)return res.status(503).json({error:'Payments unavailable'});
  let event;try{event=stripe.webhooks.constructEvent(req.body,req.headers['stripe-signature'],process.env.STRIPE_WEBHOOK_SECRET);}catch{return res.status(400).json({error:'Invalid webhook signature'});}
  if(['checkout.session.completed','checkout.session.async_payment_succeeded'].includes(event.type))await fulfill(event.data.object,event.id);
  res.json({received:true});
});
app.use(express.json({limit:'32kb'}));
app.use('/api',rateLimit({windowMs:60000,limit:240,standardHeaders:'draft-8',legacyHeaders:false}));
app.use('/api',(req,res,next)=>{
  res.set('Cache-Control','no-store');
  if(['POST','PUT','PATCH','DELETE'].includes(req.method)){
    const origin=req.headers.origin;const expected=process.env.PUBLIC_URL;
    if(req.headers['sec-fetch-site']==='cross-site'||(origin && (expected ? origin!==expected : new URL(origin).host!==req.get('host'))))return res.status(403).json({error:'Please use this site directly.'});
    if(!req.is('application/json')&&!req.is('multipart/form-data'))return res.status(415).json({error:'Unsupported request format.'});
  }
  next();
});
app.use((req,res,next)=>{
  let [visitor,signature]=(cookies(req).tla_visitor||'').split('.');
  if(!/^[a-f0-9]{64}$/.test(visitor||'') || !signature || !safeEqual(signature,signVisitor(visitor,visitorSecret))){visitor=token();setCookie(res,'tla_visitor',`${visitor}.${signVisitor(visitor,visitorSecret)}`,31536000000);}
  req.visitor=hash(visitor);next();
});
const authLimit=rateLimit({windowMs:900000,limit:20,standardHeaders:'draft-8',legacyHeaders:false});
const actionLimit=rateLimit({windowMs:60000,limit:20,keyGenerator:req=>ipKeyGenerator(req.ip),standardHeaders:'draft-8',legacyHeaders:false});
async function user(req){const s=cookies(req).tla_session;if(!s)return null;const [u]=await q('SELECT sponsors.id,sponsors.email FROM sessions JOIN sponsors ON sponsors.id=sessions.sponsor_id WHERE sessions.token=? AND sessions.expires_at>?',[hash(s),now()]);return u||null;}
async function requireUser(req,res,next){req.user=await user(req);if(!req.user)return res.status(401).json({error:'Sign in to continue.'});next();}
function requireAdmin(req,res,next){if(!process.env.ADMIN_TOKEN)return res.status(503).json({error:'Administration is not configured yet.'});const value=req.headers.authorization?.replace(/^Bearer /,'')||'';if(!safeEqual(value,process.env.ADMIN_TOKEN))return res.status(401).json({error:'Invalid administrator token.'});next();}
const account=z.object({email:z.email().max(254).transform(v=>v.toLowerCase().trim()),password:z.string().min(12).max(128)});
async function session(res,id){const t=token();await tx(db=>db('INSERT INTO sessions(token,sponsor_id,expires_at) VALUES(?,?,?)',[hash(t),id,now()+604800000]));setCookie(res,'tla_session',t,604800000);}
app.get('/api/health',async(req,res)=>{await q('SELECT id FROM app_lock WHERE id=1');res.json({status:'ok',storage:postgres?'postgresql':'sqlite',paymentsEnabled,adminConfigured:Boolean(process.env.ADMIN_TOKEN),emailEnabled:Boolean(process.env.RESEND_API_KEY&&process.env.EMAIL_FROM)});});
app.get('/api/config',(req,res)=>res.json({paymentsEnabled,emailEnabled:Boolean(process.env.RESEND_API_KEY&&process.env.EMAIL_FROM),rules:RULES,operator:{name:process.env.OPERATOR_NAME||'',email:process.env.SUPPORT_EMAIL||'',address:process.env.OPERATOR_ADDRESS||''}}));
app.get('/api/state',async(req,res)=>res.json(await state(req.visitor)));
app.get('/api/events',(req,res)=>{res.set({'Content-Type':'text/event-stream','Cache-Control':'no-cache','Connection':'keep-alive','X-Accel-Buffering':'no'});res.flushHeaders();res.write('event: refresh\ndata: {}\n\n');const interval=setInterval(()=>res.write('event: refresh\ndata: {}\n\n'),3000);req.on('close',()=>clearInterval(interval));});
app.post('/api/placements/:id/end',actionLimit,async(req,res)=>res.json(await act(req.params.id,req.visitor)));
app.post('/api/placements/:id/view',async(req,res)=>{if(!/bot|crawler|spider|preview/i.test(req.headers['user-agent']||''))await track(req.params.id,req.visitor,'view');res.json({ok:true});});
app.get('/go/:id',actionLimit,async(req,res)=>{const p=await track(req.params.id,req.visitor,'click');if(!p)return res.status(404).send('Placement not found');res.redirect(302,p.url);});
app.get('/api/archive',async(req,res)=>{const page=Math.max(0,Math.min(10000,Number(req.query.page)||0));const rows=await q("SELECT * FROM placements WHERE status='ended' ORDER BY ended_at DESC LIMIT 13 OFFSET ?",[page*12]);res.json({items:rows.slice(0,12).map(publicPlacement),hasMore:rows.length>12});});
app.get('/api/placements/:id',async(req,res)=>{const [p]=await q("SELECT * FROM placements WHERE id=? AND status IN ('live','ended','queued')",[req.params.id]);if(!p)return res.status(404).json({error:'Placement not found.'});res.json(publicPlacement(p));});
app.get('/api/me',async(req,res)=>res.json({user:await user(req)}));
app.post('/api/auth/register',authLimit,async(req,res)=>{const a=account.parse(req.body);const password=await passwordHash(a.password),id=randomUUID();try{await tx(db=>db('INSERT INTO sponsors(id,email,password,created_at) VALUES(?,?,?,?)',[id,a.email,password,now()]));}catch(e){if(e.code==='23505'||String(e.message).includes('UNIQUE'))return res.status(409).json({error:'Unable to create this account. Try signing in or resetting your password.'});throw e;}await session(res,id);res.json({user:{id,email:a.email}});});
app.post('/api/auth/login',authLimit,async(req,res)=>{const a=account.parse(req.body);const [u]=await q('SELECT * FROM sponsors WHERE email=?',[a.email]);if(!u||!await verifyPassword(a.password,u.password))return res.status(401).json({error:'Email or password is incorrect.'});await session(res,u.id);res.json({user:{id:u.id,email:u.email}});});
app.post('/api/auth/logout',async(req,res)=>{await tx(db=>db('DELETE FROM sessions WHERE token=?',[hash(cookies(req).tla_session||'')]));res.clearCookie('tla_session',{path:'/'});res.json({ok:true});});
app.post('/api/auth/forgot',authLimit,async(req,res)=>{if(!process.env.RESEND_API_KEY||!process.env.EMAIL_FROM||!process.env.PUBLIC_URL)return res.status(503).json({error:'Email recovery is not available yet. Keep your password safe.'});const email=z.email().parse(req.body.email).toLowerCase();const [u]=await q('SELECT id FROM sponsors WHERE email=?',[email]);if(u){const t=token();await tx(async db=>{await db('INSERT INTO resets(token,sponsor_id,expires_at) VALUES(?,?,?)',[hash(t),u.id,now()+1800000]);await db('INSERT INTO outbox(id,recipient,subject,body,state,created_at) VALUES(?,?,?,?,?,?)',[randomUUID(),email,'Reset your Last Ad password',`Reset your password within 30 minutes: ${process.env.PUBLIC_URL}/reset#${t}`,'pending',now()]);});}res.json({ok:true});});
app.post('/api/auth/reset',authLimit,async(req,res)=>{const a=z.object({token:z.string().length(64),password:z.string().min(12).max(128)}).parse(req.body);const password=await passwordHash(a.password);await tx(async db=>{const [r]=await db('SELECT * FROM resets WHERE token=? AND expires_at>?',[hash(a.token),now()]);if(!r)throw Object.assign(new Error('This reset link has expired.'),{status:400});await db('UPDATE sponsors SET password=? WHERE id=?',[password,r.sponsor_id]);await db('DELETE FROM sessions WHERE sponsor_id=?',[r.sponsor_id]);await db('DELETE FROM resets WHERE sponsor_id=?',[r.sponsor_id]);});res.json({ok:true});});
const creative=z.object({name:z.string().trim().min(2).max(40),headline:z.string().trim().min(5).max(90),description:z.string().trim().min(10).max(240),url:z.string().refine(validUrl,'Use a public HTTPS product URL.'),image:z.string().max(100).default(''),theme:z.enum(['red','blue','green','ink']),accepted:z.literal(true)});
app.post('/api/submissions',requireUser,async(req,res)=>{const a=creative.parse(req.body);const id=randomUUID();await tx(async db=>{const [count]=await db("SELECT COUNT(*) AS n FROM placements WHERE sponsor_id=? AND status IN ('review','approved','queued','live')",[req.user.id]);if(Number(count.n)>=10)throw Object.assign(new Error('You can have up to 10 open submissions.'),{status:429});if(a.image){const [asset]=await db('SELECT id FROM assets WHERE id=? AND sponsor_id=?',[a.image.replace('/media/',''),req.user.id]);if(!asset)throw Object.assign(new Error('Upload an image from your account.'),{status:400});}await db("INSERT INTO placements(id,sponsor_id,name,headline,description,url,image,theme,status,created_at) VALUES(?,?,?,?,?,?,?,?,'review',?)",[id,req.user.id,a.name,a.headline,a.description,a.url,a.image,a.theme,now()]);await audit(db,'submission.created',id);});res.status(201).json({id});});
const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:2*1024*1024,files:1}});
app.post('/api/upload',requireUser,upload.single('image'),async(req,res)=>{if(!req.file||!['image/jpeg','image/png','image/webp'].includes(req.file.mimetype))return res.status(400).json({error:'Choose a JPEG, PNG, or WebP under 2 MB.'});const [count]=await q('SELECT COUNT(*) AS n FROM assets WHERE sponsor_id=?',[req.user.id]);if(Number(count.n)>=20)return res.status(429).json({error:'Image limit reached. Reuse an existing image.'});let image;try{image=await sharp(req.file.buffer,{limitInputPixels:20000000}).rotate().resize(1400,1000,{fit:'inside',withoutEnlargement:true}).webp({quality:85}).toBuffer();}catch{return res.status(400).json({error:'This image could not be read.'});}const id=randomUUID();await tx(db=>db('INSERT INTO assets(id,sponsor_id,content,created_at) VALUES(?,?,?,?)',[id,req.user.id,image.toString('base64'),now()]));res.json({url:`/media/${id}`});});
app.get('/media/:id',async(req,res)=>{const [a]=await q('SELECT content FROM assets WHERE id=?',[req.params.id]);if(!a)return res.sendStatus(404);res.type('webp').set('Cache-Control','public,max-age=31536000,immutable').send(Buffer.from(a.content,'base64'));});
app.get('/api/dashboard',requireUser,async(req,res)=>{const placements=await q('SELECT * FROM placements WHERE sponsor_id=? ORDER BY created_at DESC',[req.user.id]);const payments=await q('SELECT id,placement_id,purpose,amount,state,created_at FROM payments WHERE sponsor_id=? ORDER BY created_at DESC',[req.user.id]);res.json({placements,payments,paymentsEnabled});});
app.post('/api/placements/:id/checkout',requireUser,async(req,res)=>{const purpose=z.enum(['placement','refill']).parse(req.body.purpose);res.json({url:await checkout(req.user.id,req.params.id,purpose)});});
app.post('/api/placements/:id/reuse',requireUser,async(req,res)=>{const id=randomUUID();await tx(async db=>{const [p]=await db('SELECT * FROM placements WHERE id=? AND sponsor_id=?',[req.params.id,req.user.id]);if(!p)throw Object.assign(new Error('Placement not found.'),{status:404});const [c]=await db("SELECT COUNT(*) AS n FROM placements WHERE sponsor_id=? AND status IN ('review','approved','queued','live')",[req.user.id]);if(Number(c.n)>=10)throw Object.assign(new Error('You have 10 open submissions.'),{status:429});await db("INSERT INTO placements(id,sponsor_id,name,headline,description,url,image,theme,status,created_at) VALUES(?,?,?,?,?,?,?,?,'review',?)",[id,req.user.id,p.name,p.headline,p.description,p.url,p.image,p.theme,now()]);});res.json({id});});
app.get('/api/admin',authLimit,requireAdmin,async(req,res)=>{const placements=await q('SELECT * FROM placements ORDER BY created_at DESC LIMIT 200');const events=await q('SELECT * FROM audit ORDER BY created_at DESC LIMIT 40');const payments=await q('SELECT id,placement_id,amount,state,purpose,created_at FROM payments ORDER BY created_at DESC LIMIT 100');res.json({placements,events,payments,paymentsEnabled,storage:postgres?'PostgreSQL':'SQLite — back up the persistent data directory',emailEnabled:Boolean(process.env.RESEND_API_KEY&&process.env.EMAIL_FROM)});});
app.post('/api/admin/placements/:id',authLimit,requireAdmin,async(req,res)=>{const a=z.object({action:z.enum(['approve','reject','complimentary','end','remove','move_first']),note:z.string().max(500).default('')}).parse(req.body);await tx(async db=>{const [p]=await db('SELECT * FROM placements WHERE id=?',[req.params.id]);if(!p)throw Object.assign(new Error('Placement not found.'),{status:404});if(a.action==='approve'||a.action==='reject'){if(p.status!=='review')throw Object.assign(new Error('Only pending submissions can be reviewed.'),{status:409});await db('UPDATE placements SET status=?,moderation_note=? WHERE id=?',[a.action==='approve'?'approved':'rejected',a.note,p.id]);await notify(db,p,`Your ad was ${a.action==='approve'?'approved':'declined'}`,a.action==='approve'?'Your ad is approved. Sign in to your dashboard to reserve your placement.':`Review note: ${a.note||'Please check our content rules.'}`);}else if(a.action==='complimentary'){if(!['approved','review'].includes(p.status))throw Object.assign(new Error('Only unpaid submissions can receive a complimentary placement.'),{status:409});await db("UPDATE placements SET complimentary=1 WHERE id=?",[p.id]);await enqueue(db,p.id);}else if(a.action==='end'||a.action==='remove'){if(!['live','queued'].includes(p.status))throw Object.assign(new Error('This placement is not live or queued.'),{status:409});await finish(db,p.id,'operator');await db("UPDATE placements SET moderation_note=? WHERE id=?",[a.note,p.id]);if(a.action==='remove'){await db("UPDATE placements SET name='Removed placement',headline='PLACEMENT REMOVED',description='This placement was removed by the operator.',url='/rules',image='' WHERE id=?",[p.id]);await db("UPDATE payments SET state='refund_pending' WHERE placement_id=? AND state='fulfilled'",[p.id]);}}else{if(p.status!=='queued')throw Object.assign(new Error('Only queued placements can be moved.'),{status:409});const [first]=await db("SELECT MIN(queued_at) AS first FROM placements WHERE status='queued'");await db('UPDATE placements SET queued_at=? WHERE id=?',[Number(first.first||now())-1,p.id]);}await audit(db,`admin.${a.action}`,p.id,a.note);await advance(db);});res.json({ok:true});});
function xml(s){return String(s).replace(/[<>&"']/g,c=>({'<':'&lt;','>':'&gt;','&':'&amp;','"':'&quot;',"'":'&apos;'}[c]));}
app.get('/share/:id.svg',async(req,res)=>{const [p]=await q("SELECT * FROM placements WHERE id=? AND status='ended'",[req.params.id]);if(!p)return res.sendStatus(404);const minutes=p.started_at?Math.max(1,Math.round((Number(p.ended_at)-Number(p.started_at))/60000)):0;res.type('svg').set('Content-Disposition',`attachment; filename="last-ad-${p.id}.svg"`).send(`<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="630"><rect width="1200" height="630" fill="#f4f1e9"/><rect x="32" y="32" width="1136" height="566" fill="none" stroke="#171714" stroke-width="2"/><text x="70" y="100" font-family="sans-serif" font-size="24" fill="#171714">THE LAST AD / DEATH CERTIFICATE</text><text x="70" y="220" font-family="sans-serif" font-size="64" font-weight="bold" fill="#171714">${xml(p.name)}</text><text x="70" y="340" font-family="sans-serif" font-size="100" font-weight="bold" fill="#d93624">ENDED.</text><text x="70" y="430" font-family="sans-serif" font-size="30" fill="#171714">${p.allowance-p.remaining} audience actions · ${minutes} minutes on the billboard</text><text x="70" y="535" font-family="sans-serif" font-size="22" fill="#171714">${xml(p.house?'House ad':p.complimentary?'Complimentary placement':'Sponsored placement')} · ${xml(new Date(Number(p.ended_at)).toISOString().slice(0,10))}</text></svg>`);});
app.use(express.static(resolve('dist'),{maxAge:'1h'}));
app.use('/api',(req,res)=>res.status(404).json({error:'Endpoint not found.'}));
app.get('/{*path}',(req,res)=>res.sendFile(resolve('dist/index.html')));
app.use((err,req,res,next)=>{if(err instanceof z.ZodError)return res.status(400).json({error:err.issues[0]?.message||'Check your form.'});if(err.code==='LIMIT_FILE_SIZE')return res.status(400).json({error:'Image must be smaller than 2 MB.'});const status=err.status||500;if(status===500)console.error('Request failed:',err.name);res.status(status).json({error:status===500?'Something went wrong. Please try again.':err.message});});
let mailBusy=false;
async function sendMail(){if(mailBusy||!process.env.RESEND_API_KEY||!process.env.EMAIL_FROM)return;mailBusy=true;try{const pending=await q("SELECT * FROM outbox WHERE state='pending' ORDER BY created_at LIMIT 10");for(const m of pending){const response=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${process.env.RESEND_API_KEY}`,'Content-Type':'application/json','Idempotency-Key':m.id},body:JSON.stringify({from:process.env.EMAIL_FROM,to:[m.recipient],subject:m.subject,text:m.body}),signal:AbortSignal.timeout(10000)});if(response.ok)await tx(db=>db("UPDATE outbox SET state='sent' WHERE id=?",[m.id]));}}finally{mailBusy=false;}}
const timer=setInterval(()=>tick().catch(()=>console.error('Queue advancement failed')),1000);
const worker=setInterval(()=>{paymentWorker().catch(()=>console.error('Payment reconciliation needs attention'));sendMail().catch(()=>console.error('Email delivery pending'));},30000);
const cleanup=setInterval(()=>tx(async db=>{await db('DELETE FROM sessions WHERE expires_at<?',[now()]);await db('DELETE FROM resets WHERE expires_at<?',[now()]);await db('DELETE FROM audience WHERE created_at<?',[now()-7776000000]);}).catch(()=>{}),3600000);
const server=app.listen(Number(process.env.PORT||3000),'0.0.0.0',()=>console.log(`The Last Ad listening on ${process.env.PORT||3000}; ${postgres?'PostgreSQL':'SQLite'}; payments ${paymentsEnabled?'enabled':'disabled'}`));
process.on('SIGTERM',()=>{clearInterval(timer);clearInterval(worker);clearInterval(cleanup);server.close(()=>process.exit(0));setTimeout(()=>process.exit(0),10000).unref();});
