import {useEffect,useRef,useState} from 'react';
import {Crosshair,ArrowUpRight,Check,Radio,Clock3,ArrowRight,Loader2,ShieldPlus,Skull,Trophy,Users} from 'lucide-react';
import {useLiveState} from '../hooks/useLiveState';
import {api,instrument,number,duration} from '../lib/api';
import type {Placement,Receipt} from '../lib/types';
import {Creative} from './Creative';
import {ShareControls} from './ShareControls';
import {AuctionPanel} from './AuctionPanel';
import '../viral-v2.css';
export function pressure(lives:number){if(lives<=5)return {key:'final',label:'FINAL LIVES',copy:'Every hit could be the last.'};if(lives<=25)return {key:'deathwatch',label:'DEATHWATCH',copy:`Only ${lives} people stand between this ad and death.`};if(lives<=100)return {key:'danger',label:'DANGER ZONE',copy:'The end is getting closer.'};if(lives<=200)return {key:'pressure',label:'UNDER PRESSURE',copy:'The internet is making itself heard.'};return {key:'normal',label:'ALIVE. FOR NOW.',copy:'One ad owns the page. You decide when it leaves.'};}
function hitTitle(receipt:Receipt){if(receipt.remaining===0)return 'EXECUTIONER';if(receipt.remaining<=5)return 'FINAL FIVE';if(receipt.remaining<=50)return 'FINAL 50';if(receipt.ordinal===1)return 'FIRST BLOOD';return 'ACCOMPLICE';}
type SaveReceipt={placementId:string;name:string;remaining:number;from:number};
export function LiveBillboard({notify}:{notify:(s:string)=>void}){
 const {data,error,refresh}=useLiveState();const [shown,setShown]=useState<Placement|null>(null),[death,setDeath]=useState<Placement|null>(null),[busy,setBusy]=useState(false),[receipt,setReceipt]=useState<Receipt|null>(null),[saveReceipt,setSaveReceipt]=useState<SaveReceipt|null>(null),[hit,setHit]=useState(false),[actionError,setActionError]=useState(''),[claim,setClaim]=useState(''),[claimed,setClaimed]=useState(''),[claimBusy,setClaimBusy]=useState(false);
 const lastId=useRef(''),latest=useRef(data),transition=useRef<ReturnType<typeof setTimeout>|null>(null),hitTimer=useRef<ReturnType<typeof setTimeout>|null>(null),sending=useRef(false);latest.current=data;
 const saveMode=new URLSearchParams(location.search).get('mode')==='save';
 function enter(){if(transition.current)clearTimeout(transition.current);transition.current=null;setDeath(null);setReceipt(null);setSaveReceipt(null);setClaimed('');setClaim('');if(latest.current)setShown(latest.current.current);if(location.search)history.replaceState(null,'','/');}
 useEffect(()=>{if(!data)return;const p=data.current;if(lastId.current!==p.id){const old=lastId.current;lastId.current=p.id;if(old){setDeath(data.previous?.id===old?data.previous:null);if(transition.current)clearTimeout(transition.current);transition.current=setTimeout(enter,10000);}else setShown(p);void api(`/api/placements/${p.id}/view`,'POST',{}).catch(()=>{});}else if(!transition.current)setShown(p);document.title=`${p.remaining} lives left — ${p.name} | The Last Ad`;},[data]);
 useEffect(()=>{instrument('homepage_view');return()=>{if(transition.current)clearTimeout(transition.current);if(hitTimer.current)clearTimeout(hitTimer.current);};},[]);
 async function crowdAction(){if(!data||sending.current)return;sending.current=true;setBusy(true);setActionError('');try{if(saveMode){const result=await api(`/api/placements/${data.current.id}/save`,'POST',{});if(result.counted){setSaveReceipt(result.receipt);setHit(true);hitTimer.current=setTimeout(()=>setHit(false),550);notify(`Reinforcement confirmed. ${result.receipt.remaining} lives remain.`);}else notify(result.maxed?'This ad is already at maximum life.':result.stale?'That ad has already left the stage.':'Your one action already counted.');}else{const result=await api(`/api/placements/${data.current.id}/end`,'POST',{});if(result.counted){setReceipt(result.receipt);setHit(true);hitTimer.current=setTimeout(()=>setHit(false),550);notify(result.executioner?'FINAL HIT. You killed the ad.':`Hit #${result.receipt.ordinal} confirmed. ${result.receipt.remaining} lives remain.`);}else notify(result.stale?'That ad has already left the stage.':'Your one action already counted.');}await refresh();}catch(e){setActionError((e as Error).message);}finally{sending.current=false;setBusy(false);}}
 async function claimKill(){const id=receipt?.placementId;if(!id)return;setClaimBusy(true);try{const result=await api(`/api/placements/${id}/claim`,'POST',{handle:claim});setClaimed(result.handle);notify(`Kill claimed as @${result.handle}.`);await refresh();}catch(e){setActionError((e as Error).message);}finally{setClaimBusy(false);}}
 if(!data||!shown)return <main className="page"><div className="loading"><Loader2 className="spin"/> Connecting to the billboard…</div>{error&&<p role="alert">{error} <button className="button small" onClick={refresh}>Retry</button></p>}</main>;
 const p=shown,state=pressure(p.remaining),acted=data.acted||receipt?.placementId===p.id||saveReceipt?.placementId===p.id;const label=p.house?'HOUSE AD':p.complimentary?'COMPLIMENTARY':'SPONSORED';const finalKiller=Boolean(receipt&&receipt.remaining===0&&death?.id===receipt.placementId);
 return <main className={`event-home state-${state.key} ${hit?'hit-confirmed':''} ${saveMode?'reinforcement-mode':''}`}>
  {saveMode&&<div className="reinforcement-banner"><ShieldPlus size={18}/><strong>REINFORCEMENTS ARRIVED.</strong><span>Your one action can add a life instead of taking one.</span></div>}
  <div className="broadcast-line"><span><span className="live-dot"/> LIVE NOW</span><span className="broadcast-message">ONE AD. TWO SIDES. THE INTERNET HAS THE LAST WORD.</span><span>ROUND / {p.id.slice(0,6).toUpperCase()}</span></div>
  <section className="live-arena" aria-label="Live ad and life counter"><div className="ad-stage"><div className="target-line"><h1>{p.name}</h1><span>{label}</span></div><Creative p={p}/><div className="ad-exit"><span>See it before it’s gone.</span><a href={`/go/${p.id}`} target={p.house?'_self':'_blank'} rel="noopener noreferrer">{p.house?'Put your ad here':'Visit '+p.name}<ArrowUpRight size={18}/></a></div></div><div className="life-console"><div className="danger-label">{saveMode?<ShieldPlus size={17}/>:<Crosshair size={17}/>} {saveMode?'SAVE RUN':state.label}</div><div className="life-count" key={`${p.id}:${p.remaining}`}>{p.remaining.toLocaleString('en-US')}</div><div className="lives-label">LIVES LEFT</div><div className="depletion" role="progressbar" aria-label="Lives remaining" aria-valuenow={p.remaining} aria-valuemin={0} aria-valuemax={p.allowance}><span style={{width:`${p.remaining/p.allowance*100}%`}}/></div><div className="depletion-label"><span>{number(p.allowance-p.remaining)} NET LIVES LOST</span><span>{p.allowance} MAX LIVES</span></div><button className={`take-life ${acted?'spent':''} ${saveMode?'save-action':''}`} onClick={crowdAction} disabled={acted||busy||Boolean(transition.current)}>{busy?<Loader2 className="spin" size={22}/>:acted?<Check size={22}/>:saveMode?<ShieldPlus size={22}/>:<Skull size={22}/>}<span>{acted?'YOUR ACTION COUNTED':saveMode?'SAVE THIS AD':'KILL THIS AD'}</span><strong>{acted?'✓':saveMode?'+1':'−1'}</strong></button><p className="one-hit">One browser gets one crowd action per ad. Choose a side.</p><div className="hit-receipt" aria-live="polite">{receipt?.placementId===p.id?<><span>{hitTitle(receipt)} / HIT #{receipt.ordinal}</span><strong>{receipt.from} <ArrowRight size={15}/> {receipt.remaining}</strong></>:saveReceipt?.placementId===p.id?<><span>REINFORCEMENT / VERIFIED</span><strong>{saveReceipt.from} <ArrowRight size={15}/> {saveReceipt.remaining}</strong></>:<><span>{state.copy}</span><Clock3 size={15}/></>}</div><div className="summon"><p>{acted?'DON’T STOP HERE.':saveMode?'THE BRAND CALLED FOR BACKUP.':'DON’T LET IT DIE ALONE.'}<br/><strong>{saveMode?'Send reinforcements.':'Bring someone else.'}</strong></p><ShareControls p={p} receipt={receipt} notify={notify}/></div></div>
  {death&&<div className={`death-overlay ${finalKiller?'executioner-overlay':''}`} role="status"><span className="eyebrow">{death.reason==='audience'?'THE INTERNET FINISHED IT.':death.reason==='timeout'?'TIME RAN OUT.':'THE OPERATOR ENDED IT.'}</span><h2>{death.name}<br/><em>{death.reason==='audience'?'IS DEAD.':'HAS LEFT.'}</em></h2><div className="death-stats"><span>{death.allowance-death.remaining} net hits</span><span>{duration(death)} alive</span>{death.views!=null&&<span>{number(death.views)} views</span>}{death.clicks!=null&&<span>{number(death.clicks)} visits</span>}</div>{finalKiller&&<div className="executioner-claim"><Trophy size={30}/><div><strong>YOU LANDED THE FINAL HIT.</strong><p>Claim the kill with your X handle and put your name on the permanent record.</p></div>{claimed?<div className="claimed-kill">CLAIMED BY @{claimed}</div>:<form onSubmit={e=>{e.preventDefault();void claimKill();}}><span>@</span><input value={claim} onChange={e=>setClaim(e.target.value.replace(/^@/,''))} placeholder="yourhandle" maxLength={15} pattern="[A-Za-z0-9_]{1,15}" required/><button disabled={claimBusy}>{claimBusy?<Loader2 size={16} className="spin"/>:'CLAIM THE KILL'}</button></form>}</div>}{(claimed||death.executioner)&&<p className="executioner-credit">FINAL HIT: @{claimed||death.executioner}</p>}<div className="death-share"><ShareControls p={{...death,executioner:claimed||death.executioner}} notify={notify} compact/></div><button onClick={enter}>NEXT AD ENTERING <ArrowRight size={20}/></button></div>}
  </section>
  {(error||actionError)&&<div className="error" role="alert">{actionError||error} <button className="text-button" onClick={refresh}>Reconnect</button></div>}
  <section className="crowd-strip" aria-label="Real audience activity"><div><Radio size={17}/><strong>{data.hitsLast5Minutes}</strong><span>KILLS / 5 MIN</span></div><div><ShieldPlus size={17}/><strong>{data.savesLast5Minutes}</strong><span>SAVES / 5 MIN</span></div><div><Users size={17}/><strong>{data.viewersLast5Minutes}</strong><span>RECENT VIEWERS</span></div><div className="activity-ticker">{data.activity.length?data.activity.slice(0,5).map(e=><span key={e.id}>{e.kind==='hit'?`HIT #${e.ordinal} · ${e.remaining} LEFT`:e.kind==='saved'?`REINFORCEMENT · ${e.remaining} LEFT`:e.kind==='refilled'?'+250 LIVES / REFILLED':'A NEW AD TOOK THE STAGE'}</span>):<span>Quiet right now. Be part of the next moment.</span>}</div><span className="real-label">REAL ACTIVITY ONLY</span></section>
  <AuctionPanel data={data}/><section className="normal-queue"><div><span className="eyebrow">THE NORMAL QUEUE</span><h2>{data.queueCount} ADS WAITING.</h2><p>Keep your place in line. Auctions never take two turns in a row.</p></div><ol>{data.queue.length?data.queue.map((q,i)=><li key={q.id}><span>{String(i+1).padStart(2,'0')}</span><strong>{q.name}</strong><small>{q.complimentary?'Complimentary':'Sponsored'} · 500 lives</small></li>):<li className="no-queue">The line is open. Your ad could be next.</li>}</ol><a className="button dark" href="/sponsor" onClick={()=>instrument('sponsor_cta_clicked',p.id)}>Enter the experiment <ArrowUpRight size={17}/></a></section><section className="public-record"><div className="record-heading"><span className="eyebrow">THE RECORD. NO MADE-UP NUMBERS.</span><a href="/archive">The graveyard <ArrowUpRight size={18}/></a></div><div className="record-grid"><div><strong>{number(data.stats.killed_ads)}</strong><span>ADS KILLED BY THE CROWD</span></div><div><strong>{number(data.stats.total_hits)}</strong><span>NET AUDIENCE HITS</span></div><div><strong>{number(data.stats.shared_views)}</strong><span>PUBLICLY SHARED VIEWS</span></div><div><strong>{number(data.stats.shared_clicks)}</strong><span>PUBLICLY SHARED VISITS</span></div><div><strong>{number(data.stats.refills)}</strong><span>REFILLS COMPLETED</span></div></div><p>Sponsored and complimentary placements. House ads excluded. Views and visits include only advertisers who opted to share them.</p></section>
 </main>;
}
