import {Copy,Share2,ArrowUpRight,Link} from 'lucide-react';
import {instrument,duration} from '../lib/api';
import type {Placement,Receipt} from '../lib/types';
export function ShareControls({p,receipt,notify,compact=false}:{p:Placement;receipt?:Receipt|null;notify:(s:string)=>void;compact?:boolean}){
 const url=`${location.origin}${p.status==='ended'?`/archive/${p.id}`:`/live/${p.id}/${p.remaining}`}`;
 const text=p.status==='ended'?(p.executioner?`@${p.executioner} landed the final hit on ${p.name}. It survived ${duration(p)} on The Last Ad before the internet killed it.`:`${p.name} survived ${duration(p)} on The Last Ad. ${p.allowance-p.remaining} net audience hits. See its final record.`):receipt?.placementId===p.id?(receipt.remaining===0?`I landed the FINAL HIT on ${p.name}. The ad is dead. See the record.`:`I took a life off ${p.name}. ${p.remaining} remain. Every visitor gets one hit. Help finish it.`):`${p.name} has ${p.remaining} lives left on The Last Ad. The internet decides when it dies. Take your hit.`;
 async function copy(kind='challenge'){instrument('share_clicked',p.id);try{await navigator.clipboard.writeText(kind==='link'?url:kind==='reddit'?`${p.name} is ${p.status==='ended'?'in the graveyard':`down to ${p.remaining} lives`}. One billboard, one crowd action per visitor. ${url}`:`${text} ${url}`);instrument('share_copied',p.id);notify(kind==='link'?'Link copied.':'Challenge copied. Bring someone else.');}catch{notify('Clipboard unavailable. Copy the page address to share.');}}
 async function native(){instrument('share_clicked',p.id);try{if(navigator.share)await navigator.share({title:'The Last Ad',text,url});else await copy();}catch(e){if((e as Error).name!=='AbortError')notify('Sharing unavailable. Try copying the link.');}}
 return <div className={`share-controls ${compact?'compact':''}`}><button onClick={()=>copy()} className="button share-primary"><Copy size={16}/> {p.status==='ended'?'Copy the record':'Copy challenge'}</button><button className="button" onClick={native}><Share2 size={16}/> Share</button>{!compact&&<div className="share-secondary"><a href={`https://twitter.com/intent/tweet?text=${encodeURIComponent(text)}&url=${encodeURIComponent(url)}`} target="_blank" rel="noopener noreferrer" onClick={()=>instrument('share_clicked',p.id)}>Post on X <ArrowUpRight size={14}/></a><button onClick={()=>copy('reddit')}>Reddit copy</button><button onClick={()=>copy('link')}><Link size={13}/> Copy link</button></div>}</div>;
}
